resources:
- ../../base
namePrefix: prod-
images:
- name: ghcr.io/arturjoaquim/fecaf_ambiente_devops
  newName: ghcr.io/arturjoaquim/fecaf_ambiente_devops
  newTag: c02d443
- name: 'ghcr.io/arturjoaquim/fecaf_ambiente_devops:'
  newName: ghcr.io/arturjoaquim/fecaf_ambiente_devops
  newTag: df55433
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: api-express-deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
